"""
TPC-H Data Processing Pipeline
================================
Week 3 Deliverable — Real TPC-H Data, PostgreSQL backend

Source : TPC-H CSV files generated by generate_data.py  ->  ./raw/
Steps  : Load -> Clean -> Transform -> Export processed CSVs -> Load into PostgreSQL
Output : ./processed/*_clean.csv  +  PostgreSQL database 'tpch'

Prerequisites:
    pip install -r requirements.txt
    PostgreSQL running locally (default port 5432)
    CSV files from generate_data.py in ./raw/

Run:
    python tpch_pipeline.py
"""

import pandas as pd
import sqlalchemy
import logging
from pathlib import Path
from datetime import datetime

# Config
RAW_DIR       = Path("raw")
PROCESSED_DIR = Path("processed")
LOG_FILE      = "pipeline_run.log"

PG_USER     = "postgres"
PG_PASSWORD = "theja"        # your PostgreSQL password
PG_HOST     = "localhost"
PG_PORT     = 5432
PG_DATABASE = "tpch"

PG_URL = f"postgresql+psycopg2://{PG_USER}:{PG_PASSWORD}@{PG_HOST}:{PG_PORT}/{PG_DATABASE}"

PROCESSED_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s %(message)s",
    handlers=[logging.FileHandler(LOG_FILE, encoding="utf-8"), logging.StreamHandler()]
)
log = logging.getLogger(__name__)


# Step 1: Load CSV files

def load_csv(name: str) -> pd.DataFrame:
    path = RAW_DIR / f"{name}.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing: {path}\n"
            f"Run generate_data.py first to generate the CSV files."
        )
    df = pd.read_csv(path, low_memory=False)
    log.info(f"  LOAD     {name:10s}  {len(df):>10,} rows  <- {path}")
    return df


# Step 2: Clean and transform each table

def clean_lineitem(df: pd.DataFrame) -> pd.DataFrame:
    log.info("\n[LINEITEM] cleaning...")
    n = len(df)

    df["l_shipdate"]      = pd.to_datetime(df["l_shipdate"])
    df["l_commitdate"]    = pd.to_datetime(df["l_commitdate"])
    df["l_receiptdate"]   = pd.to_datetime(df["l_receiptdate"])
    df["l_quantity"]      = pd.to_numeric(df["l_quantity"], errors="coerce")
    df["l_extendedprice"] = pd.to_numeric(df["l_extendedprice"], errors="coerce")
    df["l_discount"]      = pd.to_numeric(df["l_discount"], errors="coerce")
    df["l_tax"]           = pd.to_numeric(df["l_tax"], errors="coerce")

    df = df.dropna(subset=["l_quantity", "l_extendedprice", "l_discount", "l_tax"])
    df = df.drop_duplicates(subset=["l_orderkey", "l_linenumber"])
    df = df[df["l_quantity"] > 0]
    df = df[(df["l_discount"] >= 0) & (df["l_discount"] <= 1)]
    df = df[df["l_extendedprice"] > 0]
    df = df[df["l_shipdate"] <= df["l_receiptdate"]]

    df["l_returnflag"]   = df["l_returnflag"].str.strip()
    df["l_linestatus"]   = df["l_linestatus"].str.strip()
    df["l_shipmode"]     = df["l_shipmode"].str.strip()
    df["l_shipinstruct"] = df["l_shipinstruct"].str.strip()

    df["l_net_revenue"] = (
        df["l_extendedprice"] * (1 - df["l_discount"]) * (1 + df["l_tax"])
    ).round(2)
    df["l_ship_year"]  = df["l_shipdate"].dt.year
    df["l_ship_month"] = df["l_shipdate"].dt.month

    log.info(f"  OK lineitem   {n:>10,} -> {len(df):>10,} rows  (dropped {n - len(df):,})")
    log.info(f"     new cols : l_net_revenue, l_ship_year, l_ship_month")
    return df


def clean_orders(df: pd.DataFrame) -> pd.DataFrame:
    log.info("\n[ORDERS] cleaning...")
    n = len(df)

    df["o_orderdate"]  = pd.to_datetime(df["o_orderdate"])
    df["o_totalprice"] = pd.to_numeric(df["o_totalprice"], errors="coerce")
    df = df.dropna(subset=["o_totalprice"])
    df = df.drop_duplicates(subset=["o_orderkey"])
    df = df[df["o_totalprice"] > 0]
    df = df[df["o_orderstatus"].str.strip().isin(["F", "O", "P"])]
    df = df[df["o_orderdate"].between("1992-01-01", "1998-12-31")]

    df["o_orderstatus"]   = df["o_orderstatus"].str.strip()
    df["o_orderpriority"] = df["o_orderpriority"].str.strip()
    df["o_clerk"]         = df["o_clerk"].str.strip()
    df["o_year"]          = df["o_orderdate"].dt.year
    df["o_month"]         = df["o_orderdate"].dt.month
    df["o_quarter"]       = df["o_orderdate"].dt.quarter

    log.info(f"  OK orders     {n:>10,} -> {len(df):>10,} rows  (dropped {n - len(df):,})")
    log.info(f"     new cols : o_year, o_month, o_quarter")
    return df


def clean_customer(df: pd.DataFrame) -> pd.DataFrame:
    log.info("\n[CUSTOMER] cleaning...")
    n = len(df)

    df = df.drop_duplicates(subset=["c_custkey"])
    df["c_name"]       = df["c_name"].str.strip()
    df["c_mktsegment"] = df["c_mktsegment"].str.upper().str.strip()
    df["c_phone"]      = df["c_phone"].str.strip()
    df["c_acctbal"]    = pd.to_numeric(df["c_acctbal"], errors="coerce")
    df = df.dropna(subset=["c_acctbal"])

    valid_segs = ["AUTOMOBILE", "BUILDING", "FURNITURE", "MACHINERY", "HOUSEHOLD"]
    df = df[df["c_mktsegment"].isin(valid_segs)]

    df["c_has_debt"]     = (df["c_acctbal"] < 0).astype(int)
    df["c_balance_tier"] = pd.cut(
        df["c_acctbal"],
        bins=[-float("inf"), 0, 2500, 6000, float("inf")],
        labels=["negative", "low", "medium", "high"]
    ).astype(str)

    log.info(f"  OK customer   {n:>10,} -> {len(df):>10,} rows  (dropped {n - len(df):,})")
    log.info(f"     new cols : c_has_debt, c_balance_tier")
    return df


def clean_part(df: pd.DataFrame) -> pd.DataFrame:
    log.info("\n[PART] cleaning...")
    n = len(df)

    df = df.drop_duplicates(subset=["p_partkey"])
    df["p_retailprice"] = pd.to_numeric(df["p_retailprice"], errors="coerce")
    df["p_size"]        = pd.to_numeric(df["p_size"], errors="coerce")
    df = df.dropna(subset=["p_retailprice", "p_size"])
    df = df[(df["p_size"] > 0) & (df["p_retailprice"] > 0)]
    df["p_brand_num"]  = df["p_brand"].str.extract(r"(\d+)").astype(float)
    df["p_type_clean"] = df["p_type"].str.upper().str.strip()

    log.info(f"  OK part       {n:>10,} -> {len(df):>10,} rows  (dropped {n - len(df):,})")
    log.info(f"     new cols : p_brand_num, p_type_clean")
    return df


def clean_supplier(df: pd.DataFrame) -> pd.DataFrame:
    log.info("\n[SUPPLIER] cleaning...")
    n = len(df)

    df = df.drop_duplicates(subset=["s_suppkey"])
    df["s_name"]        = df["s_name"].str.strip()
    df["s_acctbal"]     = pd.to_numeric(df["s_acctbal"], errors="coerce")
    df = df.dropna(subset=["s_acctbal"])
    df["s_is_reliable"] = (df["s_acctbal"] > 0).astype(int)

    log.info(f"  OK supplier   {n:>10,} -> {len(df):>10,} rows  (dropped {n - len(df):,})")
    log.info(f"     new cols : s_is_reliable")
    return df


def clean_partsupp(df: pd.DataFrame) -> pd.DataFrame:
    log.info("\n[PARTSUPP] cleaning...")
    n = len(df)

    df = df.drop_duplicates(subset=["ps_partkey", "ps_suppkey"])
    df["ps_supplycost"] = pd.to_numeric(df["ps_supplycost"], errors="coerce")
    df["ps_availqty"]   = pd.to_numeric(df["ps_availqty"], errors="coerce")
    df = df.dropna(subset=["ps_supplycost", "ps_availqty"])
    df = df[(df["ps_availqty"] >= 0) & (df["ps_supplycost"] > 0)]

    log.info(f"  OK partsupp   {n:>10,} -> {len(df):>10,} rows  (dropped {n - len(df):,})")
    return df


def clean_reference(name: str, df: pd.DataFrame) -> pd.DataFrame:
    log.info(f"\n[{name.upper()}] cleaning (reference table)...")
    df = df.drop_duplicates()
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].str.strip()
    log.info(f"  OK {name:10s}  {len(df):>10,} rows")
    return df


# Step 3: Save processed CSV

def save_csv(df: pd.DataFrame, name: str):
    path = PROCESSED_DIR / f"{name}_clean.csv"
    df.to_csv(path, index=False)
    log.info(f"  SAVED    -> {path}")


# Step 4: Load into PostgreSQL

def load_to_postgres(df: pd.DataFrame, table: str, engine):
    df.to_sql(
        table,
        engine,
        if_exists="replace",
        index=False,
        chunksize=10_000,
        method="multi",
    )
    with engine.connect() as conn:
        count = conn.execute(
            sqlalchemy.text(f"SELECT COUNT(*) FROM {table}")
        ).scalar()
    log.info(f"  PG LOAD  {table:10s}  {count:>10,} rows in PostgreSQL")


# Main pipeline

def run_pipeline():
    start = datetime.now()
    log.info("=" * 65)
    log.info("TPC-H DATA PROCESSING PIPELINE  -  Week 3")
    log.info(f"Started : {start.strftime('%Y-%m-%d %H:%M:%S')}")
    log.info(f"Source  : {RAW_DIR.resolve()}/")
    log.info(f"Output  : {PROCESSED_DIR.resolve()}/  +  PostgreSQL '{PG_DATABASE}'")
    log.info("=" * 65)

    log.info("\nConnecting to PostgreSQL...")
    try:
        engine = sqlalchemy.create_engine(PG_URL)
        with engine.connect() as conn:
            conn.execute(sqlalchemy.text("SELECT 1"))
        log.info(f"  Connected to PostgreSQL at {PG_HOST}:{PG_PORT}/{PG_DATABASE}")
    except Exception as e:
        log.error(f"  Could not connect to PostgreSQL: {e}")
        log.error("  Check PG_USER / PG_PASSWORD / PG_HOST in this file")
        raise

    tables = {
        "region":   (clean_reference, "region"),
        "nation":   (clean_reference, "nation"),
        "supplier": (clean_supplier,  None),
        "part":     (clean_part,      None),
        "partsupp": (clean_partsupp,  None),
        "customer": (clean_customer,  None),
        "orders":   (clean_orders,    None),
        "lineitem": (clean_lineitem,  None),
    }

    summary = {}

    for name, (clean_fn, ref_arg) in tables.items():
        log.info(f"\n{'─' * 55}")
        raw_df = load_csv(name)

        if ref_arg is not None:
            clean_df = clean_fn(ref_arg, raw_df)
        else:
            clean_df = clean_fn(raw_df)

        save_csv(clean_df, name)
        load_to_postgres(clean_df, name, engine)
        summary[name] = len(clean_df)

    elapsed = (datetime.now() - start).total_seconds()

    log.info(f"\n{'=' * 65}")
    log.info(f"Pipeline complete in {elapsed:.1f}s")
    log.info(f"\n   Table                Rows loaded")
    log.info(f"   {'─' * 40}")
    for name, rows in summary.items():
        log.info(f"   {name:20s}  {rows:>12,}")
    log.info(f"{'=' * 65}")

    return summary


if __name__ == "__main__":
    run_pipeline()
