"""
vector_filter.py
Applies pre-computed schema vectors to select the top-K most relevant tables
for a given question. No-op when no vector file exists for the dataset/db.

Used to trim large schemas (Beaver: 97-175 tables) before sending to the LLM.
Vector files are generated by scripts/generate_schema_vectors.py.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from copy import deepcopy
from pathlib import Path

_TOKEN_RE = re.compile(r"[A-Za-z0-9_]+")
_DEFAULT_DIM = 384
DEFAULT_TOP_K = 20


def _tokenize(text: str) -> list[str]:
    tokens = []
    for raw in _TOKEN_RE.findall(text.lower()):
        tokens.extend(p for p in raw.split("_") if p)
        tokens.append(raw)
    return tokens


def _token_hash(token: str) -> int:
    digest = hashlib.blake2b(token.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big", signed=False)


def _embed(text: str, dimension: int = _DEFAULT_DIM) -> list[float]:
    vec = [0.0] * dimension
    for token in _tokenize(text):
        h = _token_hash(token)
        vec[h % dimension] += 1.0 if ((h >> 8) & 1) else -1.0
    norm = math.sqrt(sum(v * v for v in vec))
    return [round(v / norm, 8) for v in vec] if norm else vec


def _cosine(a: list[float], b: list[float]) -> float:
    return sum(x * y for x, y in zip(a, b))


def _vector_path(dataset: str, db_name: str) -> Path:
    return Path("datasets") / dataset / "schema_vector" / f"{db_name}_schema_vector.json"


def apply_vector_filter(
    schema: dict,
    dataset: str,
    db_name: str,
    question: str,
    top_k: int = DEFAULT_TOP_K,
) -> dict:
    """
    Return a schema filtered to the top_k most relevant tables for the question.
    Returns the original schema unchanged if no vector file exists for (dataset, db_name).
    """
    vpath = _vector_path(dataset, db_name)
    if not vpath.exists():
        return schema

    vector_data = json.loads(vpath.read_text(encoding="utf-8"))
    dim = int(vector_data.get("dimension", _DEFAULT_DIM))
    q_vec = _embed(question, dim)

    ranked = sorted(
        (
            {"name": t.get("name"), "score": _cosine(q_vec, t.get("vector", []))}
            for t in vector_data.get("tables", [])
        ),
        key=lambda x: x["score"],
        reverse=True,
    )

    selected_upper = {r["name"].upper() for r in ranked[:top_k] if r.get("name")}
    total = len(schema.get("tables", []))

    filtered = deepcopy(schema)
    filtered["tables"] = [t for t in schema["tables"] if t.get("name", "").upper() in selected_upper]
    filtered["selected_tables"] = sorted(t["name"] for t in filtered["tables"])
    filtered["table_selection_method"] = "schema_vector_top_k"

    print(f"  [Vector] {len(filtered['tables'])}/{total} tables selected")
    return filtered
